### ISSUE TITLE
Web app is ready but keep say "login.loginFailed"

### ISSUE THREAD

**Issue by dangky0** [h4570/armnas#15]
I run install.sh, edit cadday to /var/www/armnas/frontend/web-app

Armnas is accessible but it promt a field input, i think it for passowrd input

type password same as password when I run install.sh (step 4), but it keep return "login.loginFailed"

What i did wrong when install ? and how to fix/run armnas 

![image](https://user-images.githubusercontent.com/96066885/146633388-5f3c74f4-4dea-4a3d-a72b-d4133ffbe4ed.png)

![image](https://user-images.githubusercontent.com/96066885/146633209-bc972932-0e80-434a-b6e1-ac57e141c900.png)

I'm using a NAS L1 Pro with "Armbian_19.11.3_Chainedbox_buster_current_5.4.2" rom
Try to install in 2 device, still happen same error

Thank you

**Comment by h4570** [comment]
Hi, for me it looks that backend is not working in the background (.net). I will have a deeper look for this issue, today evening or tommorow evening. Thanks

**Comment by dnmnhat** [comment]
I had the same problem with Orange Pi Zero 2 with Orangepizero2_2.1.6_ubuntu_focal_server_linux5.13.0

![Screenshot (34)](https://user-images.githubusercontent.com/68333160/148063302-fa51bf81-acc4-4818-a17e-0aab357fd2bb.png)

**Comment by h4570** [comment]
Hello guys.

Issue was resolved.
Additionaly there are more detailed login logs in armnas log file.

Thank you for your patience.
