### ISSUE TITLE
Repo not signed

### ISSUE THREAD

**Issue by ThePigeonFormerlyKnowsAsRoy** [h4570/armnas#24]
Hi man! I'm trying to install your precious program on a rk322x-box running armbian.
There i s a problem with a not signed repository, that kick off the installation flow.
Error is (recopying by italian)

Errore GPG: https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease: Le seguenti firme non sono state verificate perchè la chiave pubblica non è disponibile: NO_PUBKEY ABA1F9B8875A6661
(Translate-ish: GPG error etc. etc. : the following signatures aren't verified because the public key isn't available: no_pubkey etc. etc.)

There is some trick I can do for continue?

Thanks for supprting, if you can.

**Comment by imbmf** [comment]
I followed caddy installation instructions and after running these commands script was able to install caddy
sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list

**Comment by ThePigeonFormerlyKnowsAsRoy** [comment]
Nice shot man! Thanks



Il giorno 25 Nov 2022, 10:41, alle ore 10:41, Miroslav Ivanov ***@***.***> ha scritto:

**Comment by h4570** [comment]
Fixed
